server:
  port: 8081

spring:
  application:
    name: auth-service

jwt:
  secret: ${JWT_SECRET}

firebase:
  service-account-path: classpath:firebase-key.json
  api-key: ${JWT_SECRET}

user-service:
  base-url: ${USER_SERVICE_URL:http://localhost:8085}
  default-avatar-url: ${USER_SERVICE_DEFAULT_AVATAR:https://ui-avatars.com/api/?name=%s&background=222831&color=f9fafb}
